site_name: NZSHM Documentation
site_url: https://gns-science.github.io/nzshm-documentation
repo_url: https://github.com/gns-science/nzshm-documentation
repo_name: gns-science/nzshm-documentation
#strict: true
nav:
  - Science Processes: index.md
  - Architecture: architecture/services.md
theme:
  name: material
  language: en
  #logo: assets/logo.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  # palette:
  #   scheme: slate

  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs.sticky
# markdown_extensions:
#   - pymdownx.emoji:
#       emoji_index: !!python/name:materialx.emoji.twemoji
#       emoji_generator: !!python/name:materialx.emoji.to_svg
#   - pymdownx.critic
#   - pymdownx.caret
#   - pymdownx.mark
#   - pymdownx.tilde
#   - pymdownx.tabbed
#   - attr_list
#   - pymdownx.arithmatex:
#       generic: true
#   - pymdownx.highlight:
#       linenums: false
#   - pymdownx.superfences
#   - pymdownx.inlinehilite
#   - pymdownx.details
#   - admonition
#   - toc:
#       baselevel: 2
#       permalink: true
#       slugify: !!python/name:pymdownx.slugs.uslugify
#   - meta
plugins:
  - include-markdown
  - search:
      lang: en
  - mermaid2:
      arguments:
        theme: |
          ^(window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) ? 'dark' : 'light'  
        securityLevel: 'loose'
  # - mkdocstrings:
  #     # watch:
# extra_javascript:
#     - https://unpkg.com/mermaid@8.7.0/dist/mermaid.min.js
extra:
  social:
    # - icon: fontawesome/brands/twitter
    #   # replace with your own tweet link below
    #   link: https://github.com/waynerv/cookiecutter-pypackage
    #   name: Tweet
    # - icon: fontawesome/brands/facebook
    #   # replace with your own facebook link below
    #   link: https://github.com/waynerv/cookiecutter-pypackage
    #   name: Facebook
    - icon: fontawesome/brands/github
      link: https://github.com/gns-science/nzshm-documentation
      name: Github
    - icon: material/email
      link: "mailto:nshm@gns.cri.nz"
  # to enable disqus, uncomment the following and put your disqus id below
  # disqus: disqus_id
# uncomment the following and put your google tracking id below to enable GA
#google_analytics:
  #- UA-xxx
  #- auto
